name: CI/CD Angular Firebase NovaTienda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Angular and Firebase CLI
        run: npm install -g @angular/cli firebase-tools

      - name: Set NG_APP_API_KEY
        run: echo "NG_APP_API_KEY=${{ secrets.NG_APP_API_KEY }}" >> $GITHUB_ENV

      - name: Build Angular app
        env:
          NG_APP_API_KEY: ${{ secrets.NG_APP_API_KEY }}
        run: |
          if [ "${GITHUB_REF##*/}" == "master" ]; then
            ng build --configuration production --define "NG_APP_API_KEY=${NG_APP_API_KEY}"
          else
            ng build --configuration dev --define "NG_APP_API_KEY=${NG_APP_API_KEY}"
          fi

      - name: Deploy to Firebase Hosting (dev target)
        if: github.ref != 'refs/heads/master'
        run: firebase deploy --only hosting:dev --project weatherly-2ea41 --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase Hosting (prod target)
        if: github.ref == 'refs/heads/master'
        run: firebase deploy --only hosting:prod --project weatherly-2ea41 --token "${{ secrets.FIREBASE_TOKEN }}"
